multinode_runfabtests.sh: Updated Kernel Space Support For Fork Check
awslabs/libfabric-ci-scripts pull request #188
Opened 2022-05-25 01:10 UTC by a-szegel

Switched existing check from looking at hardcoded OS versions to querying a kernel space function in rdma-core.

Signed-off-by: Seth Zegelstein <szegel@amazon.com>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-05-25 16:50 UTC, shijin-aws requested changes

2022-05-25 16:50 UTC, shijin-aws commented on multinode_runfabtests.sh
> +    scp fork_checker.c $host:~
This `multinode_runfabtests.sh` is executed on remote host, you would have to scp this fork_checker.c to the remote host before this whole script is executed. See this https://github.com/awslabs/libfabric-ci-scripts/blob/master/multi-node.sh#L24-L25

2022-05-26 16:38 UTC, shijin-aws approved these changes

2022-05-26 16:47 UTC, wckzhang approved these changes

2022-05-26 18:30 UTC, merged